return {
    slime={
        name='slime',
        collider={
            width=10,
            height=4,
            corner=3,
            modifiers={
                setLinearDamping=10,
                setMass=0.1,
                setBullet=true,
            },
        },
        drawData={
            xOffset=8,
            yOffset=14,
            frameWidth=16,
            frameHeight=14,
        },
        animations={
            wake={
                frames='1-4',
                row=1,
                duration=0.1,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-8',
                row=4,
                duration=0.1,
                damagingFrames={3,8}
            },
        },
        moveSpeed=50,
        attackRange=40,
        attackSpeed=1.5,
    },
}