return {
    meleeEnemy={
        name='melee_enemy',
        collider={
            width=12,
            height=5,
            corner=3,
            linearDamping=20,
            mass=0.1,
        },
        drawData={
            xOffset=5,
            yOffset=17,
            spriteSheet='meleeEnemy',
            grid='meleeEnemy',
        },
        animations={
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=4,
                duration=0.4
            },
        },
        moveSpeed=210,
    },
}