return {
    slime={
        name='slime',
        collider={
            width=10,
            height=4,
            corner=3,
            linearDamping=20,
            mass=0.1,
        },
        drawData={
            xOffset=8,
            yOffset=14,
        },
        animations={
            wake={
                frames='1-4',
                row=1,
                duration=0.1,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-7',
                row=4,
                duration=0.1
            },
        },
        moveSpeed=100,
        attackRange=30,
    },
}