return {
    ['skeletonWarrior']={
        name='skeletonWarrior',
        moveSpeed=20*60,
        health=6,
        attack={
            range=40,
            period=2,
            damage=1,
            knockback=220,
            lungeForce=500,
        },
        collider={
            w=10,
            h=6,
            class='ally',
        },
        drawData={
            frameWidth=10,
            frameHeight=17,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            lower={
                frames='7-1',
                row=1,
                duration=0.1,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=4,
                duration=0.4,
                damagingFrames={1,1}
            },
        },
        particles={
            count=100,
            spread={x=4, y=8},
            yOffset=7,
            colors={
                [0xede4da]=1,
            }
        },
    },
    ['skeletonArcher']={
        name='skeletonArcher',
        moveSpeed=19*60,
        health=3,
        attack={
            range=200,  
            period=1, 
            damage=1,
            knockback=200,
            projectile={name='arrow',xOffset=12,yOffset=-10},
        },
        collider={
            w=10,
            h=6,
            class='ally',
            losFilter='solid',
        },
        drawData={
            frameWidth=38,
            frameHeight=22,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            lower={
                frames='7-1',
                row=1,
                duration=0.1,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-4',
                row=4,
                duration={0.1,0.1,0.3,0.1},
                firingFrame=4,
            },
        },
        particles={
            count=100,
            spread={x=4, y=8},
            yOffset=7,
            colors={
                [0xede4da]=3,
                [0x8b9150]=1,
            }
        },
    },
    ['skeletonMageFire']={
        name='skeletonMageFire',
        moveSpeed=18*60,  
        health=3,
        attack={
            range=150,  
            period=1.5,   
            damage=1, 
            knockback=150,
            projectile={name='flame',xOffset=6,yOffset=-7,spread=0.3},
        },
        collider={
            w=10,
            h=6,
            class='ally',
            losFilter='solid',
        },
        drawData={
            frameWidth=24,
            frameHeight=24,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            lower={
                frames='7-1',
                row=1,
                duration=0.1,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=4,
                duration=0.4,
                firingFrame=1,
            },
        },
        particles={
            count=100,
            spread={x=4, y=8},
            yOffset=7,
            colors={
                [0xede4da]=3,
                [0xe56f4b]=1,
            }
        },
    },
    ['skeletonMageIce']={
        name='skeletonMageIce',
        moveSpeed=18*60,
        health=3,
        attack={
            range=150,  
            period=1,   
            damage=1, 
            knockback=150,
            projectile={name='icicle',xOffset=6,yOffset=-7,spread=0.3},
        },
        collider={
            w=10,
            h=6,
            class='ally',
            losFilter='solid',
        },
        drawData={
            frameWidth=24,
            frameHeight=24,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            lower={
                frames='7-1',
                row=1,
                duration=0.1,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=4,
                duration=0.4,
                firingFrame=1,
            },
        },
        particles={
            count=100,
            spread={x=4, y=8},
            yOffset=7,
            colors={
                [0xede4da]=3,
                [0x769fa6]=1,
            }
        },
    },
    ['skeletonMageElectric']={
        name='skeletonMageElectric',
        moveSpeed=18*60,    
        health=3,
        attack={
            range=100,
            period=1,
            damage=1,
            knockback=100,
            projectile={name='spark',xOffset=6,yOffset=-7,count=2,spread=0.5},
        },
        collider={
            w=10,
            h=6,
            class='ally',
            losFilter='solid',
        },
        drawData={
            frameWidth=24,
            frameHeight=24,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            lower={
                frames='7-1',
                row=1,
                duration=0.1,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=4,
                duration=0.4,
                firingFrame=1,
            },
        },
        particles={
            count=100,
            spread={x=4, y=8},
            yOffset=7,
            colors={
                [0xede4da]=3,
                [0xe3c25b]=1,
            }
        },
    },
    ['slime']={
        name='slime',
        moveSpeed=15*60,
        health=3,
        attack={
            range=40,
            period=1.5,
            damage=1,
            knockback=200,
            lungeForce=500,
        },
        collider={
            w=11,
            h=5,
            class='enemy',
            restitution=0.7,
        },
        drawData={
            frameWidth=16,
            frameHeight=14,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=2,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-8',
                row=4,
                duration=0.1,
                damagingFrames={3,8}
            },
        },
        particles={
            count=80,
            spread={x=4, y=4},
            yOffset=4,
            colors={
                [0xbda351]=3,
                [0x8b9150]=1,
            }
        },
    },
    ['pumpkin']={
        name='pumpkin',
        moveSpeed=15*60,
        health=3,
        attack={
            range=40,        
            period=2,
            damage=1,
            knockback=200,
            lungeForce=400,            
        },
        collider={
            w=12,
            h=7,
            class='enemy',
            restitution=0.7,
        },
        drawData={
            frameWidth=16,
            frameHeight=18,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=4,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=4,
                duration=0.4,
                damagingFrames={1,1}
            },
        },
        particles={
            count=80,
            spread={x=5, y=5},
            yOffset=6,
            colors={
                [0xe39347]=3,
                [0x557d55]=1,
            }
        },
    },
    ['golem']={
        name='golem',
        moveSpeed=10*60,
        kbResistance=70,
        health=10,
        attack={
            range=70,        
            period=3,
            damage=1,
            knockback=700,
            lungeForce=800,
        },
        collider={
            w=14,
            h=8,
            class='enemy',
            restitution=0,
            linearDamping=7,
        },
        drawData={
            frameWidth=18,
            frameHeight=22,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=5,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-9',
                row=4,
                duration=0.1,
                damagingFrames={4,9}
            },
        },
        particles={
            count=120,
            spread={x=5, y=8},
            yOffset=8,
            colors={
                [0x918d8d]=1,
            }
        },
    },
    ['spider']={
        name='spider',
        moveSpeed=18*60,
        health=3,
        attack={
            range=50,        
            period=1,
            damage=1,
            knockback=100,
            lungeForce=800,
        },
        collider={
            w=12,
            h=7,
            class='enemy',
            restitution=0.2,
        },
        drawData={
            frameWidth=18,
            frameHeight=16,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.07,
                visibleFrame=4,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.04,
            },
            attack={
                frames='1-2',
                row=4,
                duration=0.2,
                damagingFrames={2,2}
            },
        },
        particles={
            count=50,
            spread={x=5, y=4},
            yOffset=4,
            colors={
                [0x636167]=3,
                [0xca5954]=1,
            }
        },
    },
    ['bat']={
        name='bat',
        moveSpeed=17*60,
        health=3,
        attack={
            range=30,        
            period=1,
            damage=1,
            knockback=100,
            lungeForce=500,
        },
        collider={
            w=6,
            h=4,
            class='enemy',
            collisionFilter='enemyFlying',
            losFilter='solid',
            moveFilter='solidOrBoundary',
        },
        drawData={
            frameWidth=20,
            frameHeight=16,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.07,
                visibleFrame=4,
            },
            idle={
                frames='1-3',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-3',
                row=2,
                duration=0.07,
            },
            attack={
                frames=1,
                row=2,
                duration=0.3,
                damagingFrames={1,1}
            },
        },
        particles={
            count=40,
            spread={x=2, y=2},
            yOffset=7,
            colors={
                [0xb24c4c]=3,
                [0x636167]=1,
            }
        },
    },
    ['zombie']={
        name='zombie',
        moveSpeed=8*60,
        health=3,
        attack={
            range=30,        
            period=2,
            damage=1,
            knockback=100,
            lungeForce=500,            
        },
        collider={
            w=10,
            h=6,
            class='enemy',
        },
        drawData={
            altSpriteSheets={'zombie_2','zombie_3'},
            frameWidth=18,
            frameHeight=21,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.15,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.15,
            },
            attack={
                frames='1-4',
                row=4,
                duration={0.2,0.1,0.1,0.3},
                damagingFrames={2,4}
            },
        },
        particles={
            count=100,
            spread={x=4, y=8},
            yOffset=7,
            colors={
                [0x557d55]=4,
                [0x3b5247]=1,
                [0x737b42]=1,
            }
        },
    },
    ['possessedArcher']={
        name='possessedArcher',
        moveSpeed=15*60,     
        health=3,
        attack={
            range=140,  
            period=2, 
            damage=1,
            knockback=300,
            projectile={name='darkArrow',xOffset=12,yOffset=-10,spread=0.3},
        },
        collider={
            w=12,
            h=7,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=34,
            frameHeight=23,
        },
        animations={
            spawn={
                frames='1-9',
                row=1,
                duration=0.1,
                visibleFrame=6,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-4',
                row=4,
                duration={0.1,0.1,0.3,0.1},
                firingFrame=4,
            },
        },
        particles={
            count=100,
            spread={x=6, y=9},
            yOffset=8,
            colors={
                [0x636167]=3,
                [0x918d8d]=3,
                [0xca5954]=1,
                [0xeeb551]=1,
            }
        },
    },
    ['possessedKnight']={
        name='possessedKnight',
        moveSpeed=20*60,
        health=6,
        attack={
            range=40,        
            period=1.5,
            damage=1,
            knockback=500,
            lungeForce=700,
        },
        collider={
            w=12,
            h=7,
            class='enemy',
            restitution=0.3,
        },
        drawData={
            frameWidth=38,
            frameHeight=23,
        },
        animations={
            spawn={
                frames='1-9',
                row=1,
                duration=0.1,
                visibleFrame=5,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-4',
                row=4,
                duration={0.2,0.1,0.1,0.3},
                damagingFrames={2,4}
            },
        },
        particles={
            count=100,
            spread={x=5, y=8},
            yOffset=8,
            colors={
                [0x636167]=3,
                [0x918d8d]=3,
                [0xeeb551]=1,
            }
        },
    },
    ['undeadMiner']={
        name='undeadMiner',
        moveSpeed=10*60,
        attack={
            range=100,  
            period=2, 
            damage=1,
            knockback=150,
            projectile={name='pickaxe',xOffset=10,yOffset=-10,spread=0.8},
        },
        health=3,
        collider={
            w=10,
            h=6,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=20,
            frameHeight=24,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-3',
                row=4,
                duration={0.2,0.1,0.2},
                firingFrame=3,
            },
        },
        particles={
            count=100,
            spread={x=4, y=8},
            yOffset=7,
            colors={
                [0x557d55]=4,
                [0xe39347]=2,
                [0x575a88]=1,
            }
        },
    },    
    ['ent']={
        name='ent',
        moveSpeed=10*60,     
        health=3,
        attack={
            range=90,  
            period=2.5, 
            damage=1,
            knockback=150,
            projectile={name='apple',xOffset=10,yOffset=-10,spread=1},            
        },
        collider={
            w=16,
            h=9,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=28,
            frameHeight=32,
        },
        animations={
            spawn={
                frames='1-9',
                row=1,
                duration=0.1,
                visibleFrame=5,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=2,
                duration=0.4,
                firingFrame=1,
            },
        },
        particles={
            count=140,
            spread={x=10, y=15},
            yOffset=15,
            colors={
                [0x557d55]=2,
                [0x446350]=1,
                [0x735b42]=1,
                [0x5d483c]=1,
            }
        },
    },
    ['headlessHorseman']={
        name='headlessHorseman',
        moveSpeed=15*60,
        attack={
            range=120,  
            period=4, 
            damage=1,
            knockback=600,
            projectile={name='jack-o-lantern',xOffset=0,yOffset=-24},
        },
        health=5,
        collider={
            w=27,
            h=10,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=41,
            frameHeight=40,
        },
        animations={
            spawn={
                frames='1-11',
                row=1,
                duration=0.1,
                visibleFrame=8,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-10',
                row=4,
                duration={['1-4']=0.1,[5]=0.4,['6-10']=0.1},
                firingFrame=5,
            },
        },
        particles={
            count=200,
            spread={x=10, y=14},
            yOffset=14,
            colors={
                [0x4c4b54]=4,
                [0xe56f4b]=1,
                [0x575a88]=1,
            }
        },
        deathShake={magnitude=10},
    },
    ['slimeMatron']={
        name='slimeMatron',
        moveSpeed=10*60,
        attack={
            range=130,  
            period=5, 
            minion={name='slime',spawnPoint='facing'},
        },
        health=5,
        collider={
            w=14,
            h=5,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=16,
            frameHeight=16,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-5',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-13',
                row=4,
                duration=0.1,
                spawnMinionFrame=7,
            },
        },
        particles={
            count=100,
            spread={x=4, y=7},
            yOffset=7,
            colors={
                [0xbda351]=3,
                [0x8b9150]=1,
            }
        },
    },
    ['vampire']={
        name='vampire',
        moveSpeed=14*60,
        attack={
            range=160,  
            period=3, 
            minion={name='bat',count=2,spawnPoint='facing',startState='idle'},
        },
        health=5,
        collider={
            w=12,
            h=7,
            class='enemy',
            collisionFilter='enemyFlying',
            losFilter='solid',
            moveFilter='solidOrBoundary',
        },
        drawData={
            frameWidth=28,
            frameHeight=22,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=4,
            },
            idle={
                frames='1-3',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-3',
                row=2,
                duration=0.1,
            },
            attack={
                frames='1-18',
                row=3,
                duration={['1-8']=0.05,[9]=0.2,[10]=0.4,['11-18']=0.05},
                spawnMinionFrame=10,
            },
        },
        particles={
            count=100,
            spread={x=9, y=5},
            yOffset=12,
            colors={
                [0xb24c4c]=3,
                [0xf6f0eb]=1,
                [0x41404a]=1,
            }
        },
    },
    ['tombstone']={
        name='tombstone',
        moveSpeed=0,
        attack={
            range=100,  
            period=5, 
            minion={name='zombie',spawnPoint='random',maxDistance=20},
        },
        health=5,
        kbResistance=100,
        collider={
            w=19,
            h=7,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            altSpriteSheets={'tombstone_2','tombstone_3','tombstone_4'},
            frameWidth=19,
            frameHeight=20,
            scaleX=1,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.1,
                visibleFrame=5,
            },
            idle={
                frames=7,
                row=1,
                duration=10,
            },
            attack={
                frames=7,
                row=1,
                duration=0.1,
                spawnMinionFrame=1,
            },
        },
        particles={
            count=100,
            spread={x=6, y=8},
            yOffset=8,
            colors={
                [0x918d8d]=4,
                [0x735b42]=3,
                [0x4c4b54]=1,
            }
        },
    },
    ['spiderEgg']={
        name='spiderEgg',
        moveSpeed=0,
        health=5,
        kbResistance=100,
        attack={
            range=120,  
            period=5, 
            minion={name='spider',count=3,startState='idle'},
        },
        collider={
            w=20,
            h=8,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=24,
            frameHeight=16,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=5,
            },
            idle={
                frames=1,
                row=2,
                duration=10,
            },
            attack={
                frames='1-8',
                row=2,
                duration=0.05,
            },
        },
        particles={
            count=100,
            spread={x=10, y=6},
            yOffset=6,
            colors={
                [0x918d8d]=2,
                [0xbfb8b4]=1,
                [0x4c4b54]=1,
            }
        },
    },
    ['imp']={
        name='imp',
        moveSpeed=15*60,
        health=3,
        attack={
            range=50,
            period=1.5,
            damage=1,
            knockback=200,
            lungeForce=500,
        },
        collider={
            w=9,
            h=6,
            class='enemy',
        },
        drawData={
            frameWidth=23,
            frameHeight=26,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=4,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames=1,
                row=4,
                duration=0.4,
                damagingFrames={1,1}
            },
        },
        particles={
            count=60,
            spread={x=4, y=6},
            yOffset=6,
            colors={
                [0xe56f4b]=3,
                [0x5d483c]=1,
            }
        },
    },
    ['gnasherDemon']={
        name='gnasherDemon',
        moveSpeed=20*60,
        health=6,
        attack={
            range=70,
            period=1,
            damage=1,
            knockback=200,
            lungeForce=1000,
        },
        collider={
            w=12,
            h=7,
            class='enemy',
            restitution=0.4,
        },
        drawData={
            frameWidth=22,
            frameHeight=26,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=4,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-3',
                row=4,
                duration={0.2,0.1,0.3},
                damagingFrames={2,3}
            },
        },
        particles={
            count=120,
            spread={x=6, y=9},
            yOffset=9,
            colors={
                [0xe56f4b]=3,
                [0xf6f0eb]=1,
            }
        },
    },
    ['frankenstein']={
        name='frankenstein',
        moveSpeed=10*60,     
        kbResistance=70,
        health=5,
        attack={
            range=90,  
            period=2, 
            damage=1,
            knockback=200,
            projectile={name='blueSpark',xOffset=0,yOffset=-7,count=6,spread=6.3},
        },
        collider={
            w=20,
            h=11,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=26,
            frameHeight=30,
        },
        animations={
            spawn={
                frames='1-10',
                row=1,
                duration=0.1,
                visibleFrame=5,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-5',
                row=4,
                duration=0.1,
                firingFrame=4,
            },
        },
        particles={
            count=160,
            spread={x=10, y=14},
            yOffset=14,
            colors={
                [0x557d55]=2,
                [0x735b42]=2,
                [0x769fa6]=1,
            }
        },
        deathShake={magnitude=10},
    },
    ['werebear']={
        name='werebear',
        moveSpeed=12*60,
        kbResistance=65,
        health=100,
        attack={
            range=55,        
            period=2,
            damage=1,
            knockback=700,
            lungeForce=800,
        },
        collider={
            w=28,
            h=10,
            class='enemy',
        },
        drawData={
            frameWidth=46,
            frameHeight=25,
        },
        animations={
            spawn={
                frames='1-10',
                row=1,
                duration=0.1,
                visibleFrame=6,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-5',
                row=4,
                duration={0.2,['2-5']=0.1},
                damagingFrames={2,4}
            },
        },
        particles={
            count=160,
            spread={x=14, y=10},
            yOffset=11,
            colors={
                [0x735b42]=3,
                [0x5d483c]=1,
            }
        },
        deathShake={magnitude=10},
    },
    ['werewolf']={
        name='werewolf',
        moveSpeed=15*60,
        health=3,
        attack={
            range=45,
            period=1.5,
            damage=1,
            knockback=200,
            lungeForce=700,
        },
        collider={
            w=18,
            h=8,
            class='enemy',
        },
        drawData={
            frameWidth=30,
            frameHeight=20,
        },
        animations={
            spawn={
                frames='1-9',
                row=1,
                duration=0.1,
                visibleFrame=5,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-4',
                row=4,
                duration={0.1,0.2,0.1,0.1},
                damagingFrames={2,2}
            },
        },
        particles={
            count=80,
            spread={x=14, y=10},
            yOffset=11,
            colors={
                [0x735b42]=3,
                [0x5d483c]=1,
            }
        },
    },
    ['ghost']={
        name='ghost',
        moveSpeed=5*60,
        health=3,
        attack={
            range=50,
            period=2,
            damage=1,
            knockback=150,
            lungeForce=500,
        },
        collider={
            w=10,
            h=7,
            class='enemy',
            linearDamping=5,
            restitution=0.7,
            collisionFilter='enemyFlying',
            losFilter='solid',
            moveFilter='solidOrBoundary',
        },
        drawData={
            frameWidth=10,
            frameHeight=21,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=4,
            },
            idle={
                frames='1-12',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-12',
                row=2,
                duration=0.1,
            },
            attack={
                frames=1,
                row=2,
                duration=0.6,
                damagingFrames={1,1}
            },
            teleport={
                frames='8-1',
                row=1,
                duration=0.1,
            }
        },
        particles={
            count=100,
            spread={x=5, y=7},
            yOffset=10,
            colors={
                [0xd6cec7]=1,
            }
        },
    },
    ['poltergeist']={
        name='poltergeist',
        moveSpeed=5*60,
        health=3,
        attack={
            range=120,  
            period=2, 
            damage=1,
            knockback=250,
            projectile={name={'mug','bottle','candle'},xOffset=0,yOffset=-14,spread=0.5},            
        },
        collider={
            w=10,
            h=7,
            class='enemy',
            linearDamping=5,
            restitution=0.7,
            collisionFilter='enemyFlying',
            losFilter='solid',
            moveFilter='solidOrBoundary',
        },
        drawData={
            frameWidth=20,
            frameHeight=22,
        },
        animations={
            spawn={
                frames='1-6',
                row=1,
                duration=0.1,
                visibleFrame=3,
            },
            idle={
                frames='1-12',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-12',
                row=2,
                duration=0.1,
            },
            attack={
                frames=3,
                row=2,
                duration=0.4,
                firingFrame=1
            },
            teleport={
                frames='6-1',
                row=1,
                duration=0.1,
            }
        },
        particles={
            count=120,
            spread={x=7, y=8},
            yOffset=10,
            colors={
                [0xd6cec7]=1,
            }
        },
    },
    ['floatingEyeball']={
        name='floatingEyeball',
        moveSpeed=9*60,     
        health=3,
        attack={
            range=140,  
            period=2, 
            damage=1,
            knockback=300,
            projectile={name='laser',xOffset=0,yOffset=-10,spread=0.3},
        },
        collider={
            w=12,
            h=10,
            class='enemy',
            restitution=0.7,
            collisionFilter='enemyFlying',
            losFilter='solid',
            moveFilter='solidOrBoundary',
        },
        drawData={
            frameWidth=22,
            frameHeight=23,
        },
        animations={
            spawn={
                frames='1-7',
                row=1,
                duration=0.12,
                visibleFrame=4,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.12,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.12,
            },
            attack={
                frames=1,
                row=3,
                duration=0.4,
                firingFrame=1,
            },
        },
        particles={
            count=100,
            spread={x=8, y=9},
            yOffset=9,
            colors={
                [0xd6cec7]=2,
                [0xca5954]=2,
                [0x668da9]=1,
            }
        },
    },
    ['pyreFiend']={
        name='pyreFiend',
        moveSpeed=12*60,
        kbResistance=50,
        attack={
            range=80,  
            period=3, 
            damage=1,
            knockback=100,
            projectile={name='pyre',xOffset=0,yOffset=-14,count=3,spread=0.5},
        },
        health=20,
        collider={
            w=20,
            h=11,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=32,
            frameHeight=42,
        },
        animations={
            spawn={
                frames='1-8',
                row=1,
                duration=0.1,
                visibleFrame=4,
            },
            idle={
                frames='1-4',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-4',
                row=3,
                duration=0.1,
            },
            attack={
                frames='1-7',
                row=4,
                duration={[1]=0.2,['2-3']=0.1,[4]=0.4,['5-7']=0.1},
                firingFrame=4,
            },
        },
        particles={
            count=200,
            spread={x=10, y=13},
            yOffset=13,
            colors={
                [0xe56f4b]=3,
                [0xb24c4c]=2,
                [0xf6f0eb]=1,
            }
        },
        deathShake={magnitude=10},
    },
    ['beholder']={
        name='beholder',
        moveSpeed=9*60,
        kbResistance=50,
        attack={
            range=180,  
            period=2, 
            damage=1,
            knockback=100,
            projectile={name='orb',xOffset=0,yOffset=-16,count=3,spread=1},
        },
        health=20,
        collider={
            w=19,
            h=16,
            class='enemy',
            collisionFilter='enemyFlying',
            losFilter='solid',
            moveFilter='solidOrBoundary',
        },
        drawData={
            frameWidth=38,
            frameHeight=46,
        },
        animations={
            spawn={
                frames='1-9',
                row=1,
                duration=0.1,
                visibleFrame=4,
            },
            idle={
                frames='1-8',
                row=2,
                duration=0.12,
            },
            move={
                frames='1-8',
                row=2,
                duration=0.12,
            },
            attack={
                frames=1,
                row=2,
                duration=0.4,
                firingFrame=1,
            },
        },
        particles={
            count=200,
            spread={x=9, y=9},
            yOffset=15,
            colors={
                [0xe56f4b]=3,
                [0xb24c4c]=2,
                [0xf6f0eb]=1,
            }
        },
        deathShake={magnitude=10},
    },
    ['giantTombstone']={
        name='giantTombstone',
        moveSpeed=0,
        attack={
            range=600,  
            period=7.5, 
            minion={name='tombstone',spawnPoint='level',count=5},
        },
        health=200,
        kbResistance=100,
        collider={
            w=42,
            h=12,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=42,
            frameHeight=42,
            scaleX=1,
        },
        animations={
            spawn={
                frames='1-45',
                row=1,
                duration=0.08,
                visibleFrame=21,
            },
            idle={
                frames=45,
                row=1,
                duration=1,
            },
            attack={
                frames=45,
                row=1,
                duration=0.1,
                spawnMinionFrame=1,
            },
            dead={
                frames=45,
                row=1,
                duration=2,
            },
        },
        particles={
            count=2000,
            spread={x=21,y=21},
            yOffset=21,
            maxSpeed=40,
            colors={
                [0x918d8d]=4,
                [0x735b42]=3,
                [0x4c4b54]=1,
            }
        },
        deathShake={
            magnitude=25,
            damping=3,
        },
    },
    ['obsidianGolem']={
        name='obsidianGolem',
        moveSpeed=8*60,
        kbResistance=100,
        attack={
            range=160,
            damage=1,
            period=3,
            knockback=100,
            projectile={name='obsidianFireball',xOffset=4,yOffset=-22,count=3,spread=0.75},
            slam={
                w=114,h=64,
                damage=1,
                knockback=1000,
            },
            minion={name='golem',spawnPoint='level',count=5},
        },
        health=200,
        collider={
            w=38,
            h=16,
            class='enemy',
            losFilter='solid',
        },
        drawData={
            frameWidth=72,
            frameHeight=88,
        },
        animations={
            spawn={
                frames='1-16',
                row=1,
                duration=0.1,
                visibleFrame=9,
            },
            idle={
                frames='1-6',
                row=2,
                duration=0.1,
            },
            move={
                frames='1-6',
                row=3,
                duration=0.1,
            },
            attack={                
                firingFrame=13,             --for fireball attack
                damagingFrames={5,6},       --for groundslam attack
                frames=1,row=2,duration=1   --not used
            },
            fireball={
                frames='1-16',
                row=5,
                duration=0.1,
            },
            groundslam={
                frames='1-8',
                row=4,
                duration=0.1,
            },   
            dead={
                frames='1-12',
                row=5,
                duration=0.15,
            },
        },
        particles={
            count=2000,
            spread={x=6,y=8},
            yOffset=18,
            maxSpeed=40,
            colors={
                [0x41404a]=3,
                [0x353540]=2,
                [0xe56f4b]=1,
                [0xb24c4c]=1,
            }
        },
        deathShake={
            magnitude=25,
            damping=3,
        },
    }
}